backup/prototype_site_3/prototype_site_2/config/routes.rb
Fishingapp::Application.routes.draw do
  devise_for :users

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  devise_scope :user do
    root :to => 'devise/sessions#new'
    get 'register', :to => 'devise/registrations#new', as: :register
    get 'login', :to => 'devise/sessions#new', as: :login
    get 'logout', :to => 'devise/sessions#destroy', as: :logout
  end

end

backup/prototype_site_3/prototype_site_2/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true, length: { minimum: 2 }

  validates :user_id, presence: true
end

backup/prototype_site_3/prototype_site_2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  				  :first_name, :last_name, :profile_name, :full_name
  # attr_accessible :title, :body

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                              with: /[a-zA-Z0-9_-]+/,
                              message:'must be formatted correctly.'
                           }

  #validates_uniqueness_of :profile_name

  has_many :statuses

  def full_name 
  	first_name + " " + last_name
  end
end

backup/prototype_site_3/prototype_site_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

backup/prototype_site_3/prototype_site_2/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
      @status = Status.find(params[:id])
      @status.destroy

      respond_to do |format|
        format.html { redirect_to statuses_url }
        format.json { head :no_content }
      end
  end
end

backup/prototype_site_3/prototype_site_2/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

backup/prototype_site_3/prototype_site_2/app/helpers/statuses_helper.rb
module StatusesHelper
end

backup/prototype_site_3/prototype_site_2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fishingapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
          

	<nav class="navbar navbar-default navbar-fixed-top">
		 <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	              <span class="icon-bar"></span>
	              <span class="icon-bar"></span>
	              <span class="icon-bar"></span>
	            </button>
		 			<a href="<%= root_path %>" class="navbar-brand"> Fishing App</a>
		 	</div>
		 		<div class="collapse navbar-collapse">
		 		<ul class="nav navbar-nav">
		 		<li> <%= link_to "Register", register_path %> </li>
		 			<% if user_signed_in? %>
		 				<li> <%= link_to "All Statuses", feed_path %> </li>
		 			<% end %>
		 		</ul>
		 		<ul class="nav navbar-right">
		 			<% if user_signed_in? %>
			 			<li class="dropdown">
	  						<a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
	    						<%= current_user.full_name %> <b class="caret"></b>
	    					</a>
		  					<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
		  						<li> <%= link_to "Edit Account", edit_user_registration_path %> </li>
				 				<li> <%= link_to "Log out", logout_path %> </li>
		  					</ul>
	  					</li>
	  				<% else %>
	  				 <!-- <div class="collapse navbar-collapse"> -->
	  					<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), html: {class: "navbar-form navbar-right"}) do |f| %>
				            <div class="form-group">
				               <%= f.input :email, input_html: { class: 'form-control' },  placeholder: 'email' %>
				            </div>
				            <div class="form-group">
				              <input type="password" placeholder="Password" class="form-control">
				            </div>
				            <button type="submit" class="btn btn-success">Sign in</button>
				        </form>
				        <% end %>
				     <!-- </div> -->
  					<% end %>
  				</div><!--/.nav-collapse -->
  				</ul>
		 	</div>
		 </div>
	</nav>
<div class="container">

	<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %>"> 
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= message %>
		</div>
	<% end %>

	<%= yield %> <!-- where all the views go -->
</div>
</body>
</html>