backup/prototype_site_2.2/raw_site/config/routes.rb
Fishingapp::Application.routes.draw do

  devise_for :users

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  devise_scope :user do
    root :to => 'statuses#index'
    get 'register', :to => 'devise/registrations#new', as: :register
    get 'login', :to => 'devise/sessions#new', as: :login
    get 'logout', :to => 'devise/sessions#destroy', as: :logout
  end

  get "profiles/show"
  get '/:id', to: 'profiles#show'

end

backup/prototype_site_2.2/raw_site/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true, length: { minimum: 2 }

  validates :user_id, presence: true
end

backup/prototype_site_2.2/raw_site/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  				  :first_name, :last_name, :profile_name, :full_name
  # attr_accessible :title, :body

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                              with: /^[a-zA-Z0-9_-]+$/,
                              message:'must be formatted correctly.'
                           }

  #validates_uniqueness_of :profile_name

  has_many :statuses

  def full_name 
  	first_name + " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}?d=identicon"
  end

end

backup/prototype_site_2.2/raw_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

backup/prototype_site_2.2/raw_site/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
 	 end
  end

end

backup/prototype_site_2.2/raw_site/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
      @status = Status.find(params[:id])
      @status.destroy

      respond_to do |format|
        format.html { redirect_to statuses_url }
        format.json { head :no_content }
      end
  end
end

backup/prototype_site_2.2/raw_site/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

backup/prototype_site_2.2/raw_site/app/helpers/profiles_helper.rb
module ProfilesHelper
end

backup/prototype_site_2.2/raw_site/app/helpers/statuses_helper.rb
module StatusesHelper
end

backup/prototype_site_2.2/raw_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fish Pages</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="navbar-inner">
			<div class="container">
		 		<a href="<%= root_path %>" class="brand">Fish Pages</a>
		 		<ul class="nav">
		 			<li><%= link_to "Sign Up", register_path %> </li>
		 			<li><%= link_to "All Catches", register_path %> </li>
		 			<% if user_signed_in? %>
		 				<li> <%= link_to "All Catches", feed_path %> </li>
		 			<% end %>
		 		</ul>
		 		<ul class="nav pull-right">
		 			<% if user_signed_in? %>
			 			<li class="dropdown">
	  						<a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
	    						<%= current_user.full_name %> <b class="caret"></b>
	    					</a>
		  					<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
		  						<li> <%= link_to "Edit Account", edit_user_registration_path %> </li>
				 				<li> <%= link_to "Log out", logout_path %> </li>
		  					</ul>
	  					</li>
	  				<% else %>
	  					<li> <%= link_to "Register", register_path %> </li>
	  					<li> <%= link_to "Log in", login_path %> </li>

  					<% end %>
  				</ul>
		 	</div>
		 </div>
	</nav>
<div class="container">

	<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %>"> 
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= message %>
		</div>
	<% end %>

	<%= yield %>
</div>
</body>
</html>

backup/prototype_site_2.2/raw_site/app/views/profiles/show.html.erb
<div class="page-header">
	<h1> <%= @user.full_name %> </h1>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			</hr>
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>
<% end %>